命令稿啟動於 2018年03月15日 上午 12:46:37
]0;~
[32mAmy Wu@DESKTOP-HE4KMDM [33m~[0m
$ whoami;pwd
Amy Wu
/home/Amy Wu
]0;~
[32mAmy Wu@DESKTOP-HE4KMDM [33m~[0m
$ git config -l
]0;~
[32mAmy Wu@DESKTOP-HE4KMDM [33m~[0m
$ git clone https://github.com/HI[KAIN[K[K[KainanG/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32mAmy Wu@DESKTOP-HE4KMDM [33m~[0m
$ exit

命令稿已於 2018年03月15日 上午 12:47:58
 完成